name: Test

on:
  push:
jobs:
  test:
    name: CI Build
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      pull-requests: write
    steps:
      # Hack: Maximize Disk space for big & legacy projects (May become unsupported in future Azure runner releases)
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        if: false
        with:
          root-reserve-mb: 2048
          temp-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: 'true'
      # Checkout Repository (Shallow clone is disabled due to partial builds Checks)
      - name: Checkout repository
        uses: actions/checkout@v4
      # Setup JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
      # Setup Maven
      - name: Set up Maven 3.9.9
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3